/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PrintRouteImport } from './routes/_print'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppCustomersNewRouteImport } from './routes/_app/customers/new'
import { Route as AppDriversIndexRouteImport } from './routes/_app/drivers/index'
import { Route as AppItemsIndexRouteImport } from './routes/_app/items/index'
import { Route as AppItemsNewRouteImport } from './routes/_app/items/new'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppOrdersNewRouteImport } from './routes/_app/orders/new'
import { Route as AppPaymentsNewRouteImport } from './routes/_app/payments/new'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppReportsActivityRouteImport } from './routes/_app/reports/activity'
import { Route as AppReportsPositionsRouteImport } from './routes/_app/reports/positions'
import { Route as AppReportsPurchasesRouteImport } from './routes/_app/reports/purchases'
import { Route as AppReportsStockRouteImport } from './routes/_app/reports/stock'
import { Route as AppReturnsNewRouteImport } from './routes/_app/returns/new'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppUsersNewRouteImport } from './routes/_app/users/new'
import { Route as AppCustomersCustomerIdIndexRouteImport } from './routes/_app/customers/$customerId/index'
import { Route as AppCustomersCustomerIdEditRouteImport } from './routes/_app/customers/$customerId/edit'
import { Route as AppItemsItemIdIndexRouteImport } from './routes/_app/items/$itemId/index'
import { Route as AppItemsItemIdEditRouteImport } from './routes/_app/items/$itemId/edit'
import { Route as AppOrdersOrderIdIndexRouteImport } from './routes/_app/orders/$orderId/index'
import { Route as AppOrdersOrderIdEditRouteImport } from './routes/_app/orders/$orderId/edit'
import { Route as PrintPrintOrdersOrderIdRouteImport } from './routes/_print/print/orders/$orderId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/_print',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversIndexRoute = AppDriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsIndexRoute = AppItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsNewRoute = AppItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsNewRoute = AppPaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsActivityRoute = AppReportsActivityRouteImport.update({
  id: '/reports/activity',
  path: '/reports/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsPositionsRoute = AppReportsPositionsRouteImport.update({
  id: '/reports/positions',
  path: '/reports/positions',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsPurchasesRoute = AppReportsPurchasesRouteImport.update({
  id: '/reports/purchases',
  path: '/reports/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsStockRoute = AppReportsStockRouteImport.update({
  id: '/reports/stock',
  path: '/reports/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsNewRoute = AppReturnsNewRouteImport.update({
  id: '/returns/new',
  path: '/returns/new',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersNewRoute = AppUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdIndexRoute =
  AppCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCustomersCustomerIdEditRoute =
  AppCustomersCustomerIdEditRouteImport.update({
    id: '/customers/$customerId/edit',
    path: '/customers/$customerId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppItemsItemIdIndexRoute = AppItemsItemIdIndexRouteImport.update({
  id: '/items/$itemId/',
  path: '/items/$itemId/',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsItemIdEditRoute = AppItemsItemIdEditRouteImport.update({
  id: '/items/$itemId/edit',
  path: '/items/$itemId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdIndexRoute = AppOrdersOrderIdIndexRouteImport.update({
  id: '/orders/$orderId/',
  path: '/orders/$orderId/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdEditRoute = AppOrdersOrderIdEditRouteImport.update({
  id: '/orders/$orderId/edit',
  path: '/orders/$orderId/edit',
  getParentRoute: () => AppRoute,
} as any)
const PrintPrintOrdersOrderIdRoute = PrintPrintOrdersOrderIdRouteImport.update({
  id: '/print/orders/$orderId',
  path: '/print/orders/$orderId',
  getParentRoute: () => PrintRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/history': typeof AppHistoryRoute
  '/settings': typeof AppSettingsRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/items/new': typeof AppItemsNewRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/payments/new': typeof AppPaymentsNewRoute
  '/reports/activity': typeof AppReportsActivityRoute
  '/reports/positions': typeof AppReportsPositionsRoute
  '/reports/purchases': typeof AppReportsPurchasesRoute
  '/reports/stock': typeof AppReportsStockRoute
  '/returns/new': typeof AppReturnsNewRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/new': typeof AppUsersNewRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/drivers/': typeof AppDriversIndexRoute
  '/items/': typeof AppItemsIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/customers/$customerId/edit': typeof AppCustomersCustomerIdEditRoute
  '/items/$itemId/edit': typeof AppItemsItemIdEditRoute
  '/orders/$orderId/edit': typeof AppOrdersOrderIdEditRoute
  '/print/orders/$orderId': typeof PrintPrintOrdersOrderIdRoute
  '/customers/$customerId/': typeof AppCustomersCustomerIdIndexRoute
  '/items/$itemId/': typeof AppItemsItemIdIndexRoute
  '/orders/$orderId/': typeof AppOrdersOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/history': typeof AppHistoryRoute
  '/settings': typeof AppSettingsRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/items/new': typeof AppItemsNewRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/payments/new': typeof AppPaymentsNewRoute
  '/reports/activity': typeof AppReportsActivityRoute
  '/reports/positions': typeof AppReportsPositionsRoute
  '/reports/purchases': typeof AppReportsPurchasesRoute
  '/reports/stock': typeof AppReportsStockRoute
  '/returns/new': typeof AppReturnsNewRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/new': typeof AppUsersNewRoute
  '/customers': typeof AppCustomersIndexRoute
  '/drivers': typeof AppDriversIndexRoute
  '/items': typeof AppItemsIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/customers/$customerId/edit': typeof AppCustomersCustomerIdEditRoute
  '/items/$itemId/edit': typeof AppItemsItemIdEditRoute
  '/orders/$orderId/edit': typeof AppOrdersOrderIdEditRoute
  '/print/orders/$orderId': typeof PrintPrintOrdersOrderIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdIndexRoute
  '/items/$itemId': typeof AppItemsItemIdIndexRoute
  '/orders/$orderId': typeof AppOrdersOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_print': typeof PrintRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/items/new': typeof AppItemsNewRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/payments/new': typeof AppPaymentsNewRoute
  '/_app/reports/activity': typeof AppReportsActivityRoute
  '/_app/reports/positions': typeof AppReportsPositionsRoute
  '/_app/reports/purchases': typeof AppReportsPurchasesRoute
  '/_app/reports/stock': typeof AppReportsStockRoute
  '/_app/returns/new': typeof AppReturnsNewRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/users/new': typeof AppUsersNewRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/drivers/': typeof AppDriversIndexRoute
  '/_app/items/': typeof AppItemsIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/customers/$customerId/edit': typeof AppCustomersCustomerIdEditRoute
  '/_app/items/$itemId/edit': typeof AppItemsItemIdEditRoute
  '/_app/orders/$orderId/edit': typeof AppOrdersOrderIdEditRoute
  '/_print/print/orders/$orderId': typeof PrintPrintOrdersOrderIdRoute
  '/_app/customers/$customerId/': typeof AppCustomersCustomerIdIndexRoute
  '/_app/items/$itemId/': typeof AppItemsItemIdIndexRoute
  '/_app/orders/$orderId/': typeof AppOrdersOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/account'
    | '/history'
    | '/settings'
    | '/customers/new'
    | '/items/new'
    | '/orders/new'
    | '/payments/new'
    | '/reports/activity'
    | '/reports/positions'
    | '/reports/purchases'
    | '/reports/stock'
    | '/returns/new'
    | '/users/$userId'
    | '/users/new'
    | '/customers/'
    | '/drivers/'
    | '/items/'
    | '/orders/'
    | '/reports/'
    | '/users/'
    | '/customers/$customerId/edit'
    | '/items/$itemId/edit'
    | '/orders/$orderId/edit'
    | '/print/orders/$orderId'
    | '/customers/$customerId/'
    | '/items/$itemId/'
    | '/orders/$orderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/account'
    | '/history'
    | '/settings'
    | '/customers/new'
    | '/items/new'
    | '/orders/new'
    | '/payments/new'
    | '/reports/activity'
    | '/reports/positions'
    | '/reports/purchases'
    | '/reports/stock'
    | '/returns/new'
    | '/users/$userId'
    | '/users/new'
    | '/customers'
    | '/drivers'
    | '/items'
    | '/orders'
    | '/reports'
    | '/users'
    | '/customers/$customerId/edit'
    | '/items/$itemId/edit'
    | '/orders/$orderId/edit'
    | '/print/orders/$orderId'
    | '/customers/$customerId'
    | '/items/$itemId'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/_app'
    | '/_print'
    | '/change-password'
    | '/login'
    | '/_app/account'
    | '/_app/history'
    | '/_app/settings'
    | '/_app/'
    | '/_app/customers/new'
    | '/_app/items/new'
    | '/_app/orders/new'
    | '/_app/payments/new'
    | '/_app/reports/activity'
    | '/_app/reports/positions'
    | '/_app/reports/purchases'
    | '/_app/reports/stock'
    | '/_app/returns/new'
    | '/_app/users/$userId'
    | '/_app/users/new'
    | '/_app/customers/'
    | '/_app/drivers/'
    | '/_app/items/'
    | '/_app/orders/'
    | '/_app/reports/'
    | '/_app/users/'
    | '/_app/customers/$customerId/edit'
    | '/_app/items/$itemId/edit'
    | '/_app/orders/$orderId/edit'
    | '/_print/print/orders/$orderId'
    | '/_app/customers/$customerId/'
    | '/_app/items/$itemId/'
    | '/_app/orders/$orderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PrintRoute: typeof PrintRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_print': {
      id: '/_print'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drivers/': {
      id: '/_app/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof AppDriversIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/items/': {
      id: '/_app/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof AppItemsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/items/new': {
      id: '/_app/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof AppItemsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/new': {
      id: '/_app/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof AppPaymentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/activity': {
      id: '/_app/reports/activity'
      path: '/reports/activity'
      fullPath: '/reports/activity'
      preLoaderRoute: typeof AppReportsActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/positions': {
      id: '/_app/reports/positions'
      path: '/reports/positions'
      fullPath: '/reports/positions'
      preLoaderRoute: typeof AppReportsPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/purchases': {
      id: '/_app/reports/purchases'
      path: '/reports/purchases'
      fullPath: '/reports/purchases'
      preLoaderRoute: typeof AppReportsPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/stock': {
      id: '/_app/reports/stock'
      path: '/reports/stock'
      fullPath: '/reports/stock'
      preLoaderRoute: typeof AppReportsStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns/new': {
      id: '/_app/returns/new'
      path: '/returns/new'
      fullPath: '/returns/new'
      preLoaderRoute: typeof AppReturnsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/new': {
      id: '/_app/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AppUsersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId/': {
      id: '/_app/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof AppCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId/edit': {
      id: '/_app/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof AppCustomersCustomerIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/items/$itemId/': {
      id: '/_app/items/$itemId/'
      path: '/items/$itemId'
      fullPath: '/items/$itemId/'
      preLoaderRoute: typeof AppItemsItemIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/items/$itemId/edit': {
      id: '/_app/items/$itemId/edit'
      path: '/items/$itemId/edit'
      fullPath: '/items/$itemId/edit'
      preLoaderRoute: typeof AppItemsItemIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId/': {
      id: '/_app/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId/'
      preLoaderRoute: typeof AppOrdersOrderIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId/edit': {
      id: '/_app/orders/$orderId/edit'
      path: '/orders/$orderId/edit'
      fullPath: '/orders/$orderId/edit'
      preLoaderRoute: typeof AppOrdersOrderIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_print/print/orders/$orderId': {
      id: '/_print/print/orders/$orderId'
      path: '/print/orders/$orderId'
      fullPath: '/print/orders/$orderId'
      preLoaderRoute: typeof PrintPrintOrdersOrderIdRouteImport
      parentRoute: typeof PrintRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersNewRoute: typeof AppCustomersNewRoute
  AppItemsNewRoute: typeof AppItemsNewRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppPaymentsNewRoute: typeof AppPaymentsNewRoute
  AppReportsActivityRoute: typeof AppReportsActivityRoute
  AppReportsPositionsRoute: typeof AppReportsPositionsRoute
  AppReportsPurchasesRoute: typeof AppReportsPurchasesRoute
  AppReportsStockRoute: typeof AppReportsStockRoute
  AppReturnsNewRoute: typeof AppReturnsNewRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersNewRoute: typeof AppUsersNewRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDriversIndexRoute: typeof AppDriversIndexRoute
  AppItemsIndexRoute: typeof AppItemsIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppCustomersCustomerIdEditRoute: typeof AppCustomersCustomerIdEditRoute
  AppItemsItemIdEditRoute: typeof AppItemsItemIdEditRoute
  AppOrdersOrderIdEditRoute: typeof AppOrdersOrderIdEditRoute
  AppCustomersCustomerIdIndexRoute: typeof AppCustomersCustomerIdIndexRoute
  AppItemsItemIdIndexRoute: typeof AppItemsItemIdIndexRoute
  AppOrdersOrderIdIndexRoute: typeof AppOrdersOrderIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersNewRoute: AppCustomersNewRoute,
  AppItemsNewRoute: AppItemsNewRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppPaymentsNewRoute: AppPaymentsNewRoute,
  AppReportsActivityRoute: AppReportsActivityRoute,
  AppReportsPositionsRoute: AppReportsPositionsRoute,
  AppReportsPurchasesRoute: AppReportsPurchasesRoute,
  AppReportsStockRoute: AppReportsStockRoute,
  AppReturnsNewRoute: AppReturnsNewRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersNewRoute: AppUsersNewRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDriversIndexRoute: AppDriversIndexRoute,
  AppItemsIndexRoute: AppItemsIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppCustomersCustomerIdEditRoute: AppCustomersCustomerIdEditRoute,
  AppItemsItemIdEditRoute: AppItemsItemIdEditRoute,
  AppOrdersOrderIdEditRoute: AppOrdersOrderIdEditRoute,
  AppCustomersCustomerIdIndexRoute: AppCustomersCustomerIdIndexRoute,
  AppItemsItemIdIndexRoute: AppItemsItemIdIndexRoute,
  AppOrdersOrderIdIndexRoute: AppOrdersOrderIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PrintRouteChildren {
  PrintPrintOrdersOrderIdRoute: typeof PrintPrintOrdersOrderIdRoute
}

const PrintRouteChildren: PrintRouteChildren = {
  PrintPrintOrdersOrderIdRoute: PrintPrintOrdersOrderIdRoute,
}

const PrintRouteWithChildren = PrintRoute._addFileChildren(PrintRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PrintRoute: PrintRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
