import { Controller, Get, Module } from '@nestjs/common';
import type { NestExpressApplication } from '@nestjs/platform-express';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { AppModule } from '../../src/app.module';
import { configureApp } from '../../src/bootstrap';
import { RequestContext, type RequestContextData } from '../../src/common/context/request-context';
import { ENV, type Env } from '../../src/config/env';
import { Public } from '../../src/common/decorators/access.decorators';

/**
 * Reports what the request context holds while a real request is being served. Without it a
 * middleware that is registered but never matched would go unnoticed: audit rows would simply
 * carry no ip and no request id.
 */
@Controller('test-context')
class ContextProbeController {
  @Get()
  @Public()
  read(): RequestContextData | null {
    return RequestContext.get() ?? null;
  }
}

@Module({ imports: [AppModule], controllers: [ContextProbeController] })
class ProbeModule {}

describe('request context', () => {
  let app: NestExpressApplication;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({ imports: [ProbeModule] }).compile();
    app = moduleRef.createNestApplication<NestExpressApplication>({ logger: false });
    configureApp(app, app.get<Env>(ENV));
    await app.init();
  });

  afterAll(async () => {
    await app.close();
  });

  it('is open during a request, carrying the server request id and the client ip', async () => {
    const response = await request(app.getHttpServer())
      .get('/api/test-context')
      .set('X-Request-Id', 'client-supplied-id')
      .expect(200);

    // The id is generated by the server and echoed in the header: the audit log's correlation
    // column must not be something a client can choose (§10.6 D8).
    expect(response.body).toMatchObject({ ip: expect.any(String), userId: null });
    expect(response.body.requestId).not.toBe('client-supplied-id');
    expect(response.body.requestId).toBe(response.headers['x-request-id']);
    expect(response.body.requestId).toMatch(/^[0-9a-f-]{36}$/);
  });
});
